"""Exact symbolic multigraded resolutions for small Stanley-Reisner fans.

The Parameter-Golf trainer cannot call a computer-algebra system inside the
inner loop, but the fan used by the CCA bridge is tiny and combinatorial.  This
module computes exact finite invariants for that fan:

* the Stanley-Reisner nonface generators;
* Hochster multigraded Betti numbers of ``k[Delta]`` over ``F_2``;
* Taylor free-resolution ranks for the monomial ideal ``I_Delta``.

The minimal Betti table is symbolic and exact for the finite simplicial complex
being audited.  The Taylor resolution is generally nonminimal, but it is a full
free resolution by construction and gives a useful nonminimality pressure.
"""

from __future__ import annotations

import functools
import math
from dataclasses import dataclass
from itertools import combinations


@dataclass(frozen=True)
class SymbolicResolutionMetrics:
    num_vertices: int
    nonface_generator_count: int
    minimal_total_betti: int
    minimal_positive_betti: int
    taylor_total_rank_log2: float
    taylor_positive_rank_log2: float
    taylor_boundary_terms_log2: float
    nonminimality_log2: float
    projective_dimension: int
    regularity: int
    betti0: int
    betti1: int
    betti2: int
    top_multidegree_cardinality: int
    betti_entropy: float


def mask_vertices(mask: int, num_vertices: int | None = None) -> tuple[int, ...]:
    """Return the ordered vertices contained in a squarefree monomial mask."""

    width = int(num_vertices) if num_vertices is not None else max(1, int(mask).bit_length())
    return tuple(index for index in range(width) if int(mask) & (1 << index))


def squarefree_monomial(mask: int, num_vertices: int | None = None) -> str:
    """Return a readable squarefree monomial for a bitmask multidegree."""

    vertices = mask_vertices(mask, num_vertices)
    if not vertices:
        return "1"
    return "*".join(f"x_{index}" for index in vertices)


def squarefree_exponent_vector(mask: int, num_vertices: int) -> tuple[int, ...]:
    """Return the Z^n multidegree vector of a squarefree monomial mask."""

    n = max(1, int(num_vertices))
    return tuple(1 if int(mask) & (1 << index) else 0 for index in range(n))


def cyclic_flag_faces(num_vertices: int) -> frozenset[int]:
    """Return the flag complex generated by a cyclic fan graph.

    Faces are encoded as bitmasks.  The empty face is included.  For the cyclic
    graph with ``n >= 4`` there are no triangles; the generic clique enumerator
    is retained because it makes the exact complex definition explicit.
    """

    n = max(1, int(num_vertices))
    allowed_edges: set[int] = set()
    for i in range(n):
        allowed_edges.add((1 << i) | (1 << ((i + 1) % n)))
    faces: set[int] = {0}
    for mask in range(1, 1 << n):
        vertices = [i for i in range(n) if mask & (1 << i)]
        ok = True
        for a, b in combinations(vertices, 2):
            edge = (1 << a) | (1 << b)
            if edge not in allowed_edges:
                ok = False
                break
        if ok:
            faces.add(mask)
    return frozenset(faces)


@functools.lru_cache(maxsize=64)
def cyclic_flag_face_rows(num_vertices: int) -> tuple[tuple[int, int, int], ...]:
    """Rows ``(dimension, mask, cardinality)`` for the cyclic flag complex."""

    faces = cyclic_flag_faces(num_vertices)
    rows = []
    for mask in sorted(faces, key=lambda item: (item.bit_count(), item)):
        cardinality = int(mask).bit_count()
        dimension = cardinality - 1
        rows.append((int(dimension), int(mask), int(cardinality)))
    return tuple(rows)


def stanley_reisner_nonfaces(num_vertices: int, faces: frozenset[int]) -> tuple[int, ...]:
    """Return minimal squarefree nonfaces of a complex encoded by bitmasks."""

    n = max(1, int(num_vertices))
    nonfaces: list[int] = []
    for mask in range(1, 1 << n):
        if mask in faces:
            continue
        minimal = True
        sub = (mask - 1) & mask
        while sub:
            if sub not in faces:
                minimal = False
                break
            sub = (sub - 1) & mask
        if minimal:
            nonfaces.append(mask)
    return tuple(sorted(nonfaces, key=lambda item: (item.bit_count(), item)))


@functools.lru_cache(maxsize=64)
def cyclic_stanley_reisner_generator_masks(num_vertices: int) -> tuple[int, ...]:
    """Minimal squarefree monomial generators of the cyclic fan SR ideal."""

    n = max(1, int(num_vertices))
    return stanley_reisner_nonfaces(n, cyclic_flag_faces(n))


@functools.lru_cache(maxsize=64)
def cyclic_taylor_multidegree_counts(num_vertices: int) -> tuple[tuple[int, int, int], ...]:
    """Compressed exact Taylor-resolution multidegree counts.

    Each tuple is ``(homological_degree, squarefree_lcm_mask, multiplicity)``.
    This represents every Taylor basis element without enumerating all
    ``2^g`` subsets of the monomial generators.
    """

    generators = cyclic_stanley_reisner_generator_masks(num_vertices)
    counts: dict[int, dict[int, int]] = {0: {0: 1}}
    for generator in generators:
        updated = {degree: values.copy() for degree, values in counts.items()}
        for degree, values in counts.items():
            target = updated.setdefault(degree + 1, {})
            for mask, multiplicity in values.items():
                lcm_mask = mask | generator
                target[lcm_mask] = target.get(lcm_mask, 0) + multiplicity
        counts = updated
    rows: list[tuple[int, int, int]] = []
    for degree in sorted(counts):
        if degree == 0:
            continue
        for mask, multiplicity in sorted(counts[degree].items()):
            rows.append((int(degree), int(mask), int(multiplicity)))
    return tuple(rows)


@functools.lru_cache(maxsize=64)
def cyclic_taylor_rank_rows(num_vertices: int) -> tuple[tuple[int, int, int], ...]:
    """Exact Taylor ranks and differential term counts by homological degree.

    Each row is ``(degree, rank, outgoing_boundary_terms)`` for the Taylor
    resolution of ``S / I_Delta``.  It is computed from the number of minimal
    Stanley-Reisner generators and therefore represents the full Taylor
    complex without enumerating every basis element when only aggregate ranks
    are needed.
    """

    generator_count = len(cyclic_stanley_reisner_generator_masks(num_vertices))
    rows = [(0, 1, 0)]
    for degree in range(1, generator_count + 1):
        rank = math.comb(generator_count, degree)
        rows.append((int(degree), int(rank), int(degree * rank)))
    return tuple(rows)


@functools.lru_cache(maxsize=64)
def cyclic_taylor_dg_differential_rows(num_vertices: int) -> tuple[tuple[int, int, int, int, int], ...]:
    """Compressed exact multigraded Taylor DG differential entries.

    For the Taylor map ``d_p: T_p -> T_{p-1}``, each matrix entry is the
    monomial quotient ``lcm(A) / lcm(A \\ {i})``.  Rows are compressed as
    ``(homological_degree, source_lcm_mask, target_lcm_mask, quotient_mask,
    multiplicity)`` and represent every DG differential entry exactly without
    materializing the huge sparse Taylor matrix.
    """

    n = max(1, int(num_vertices))
    generators = cyclic_stanley_reisner_generator_masks(n)
    generator_count = len(generators)
    if generator_count == 0:
        return tuple()

    subset_count = 1 << generator_count
    subset_lcms = [0] * subset_count
    for subset in range(1, subset_count):
        low_bit = subset & -subset
        index = low_bit.bit_length() - 1
        subset_lcms[subset] = subset_lcms[subset ^ low_bit] | generators[index]

    counts: dict[tuple[int, int, int, int], int] = {}
    for subset in range(1, subset_count):
        degree = subset.bit_count()
        lcm = subset_lcms[subset]
        active = subset
        while active:
            low_bit = active & -active
            previous = subset ^ low_bit
            target_lcm = subset_lcms[previous]
            quotient = lcm & ~target_lcm
            key = (int(degree), int(lcm), int(target_lcm), int(quotient))
            counts[key] = counts.get(key, 0) + 1
            active ^= low_bit

    return tuple(
        (degree, source_lcm, target_lcm, quotient, multiplicity)
        for (degree, source_lcm, target_lcm, quotient), multiplicity in sorted(counts.items())
    )


@functools.lru_cache(maxsize=64)
def cyclic_taylor_fitting_entry_ideal_rows(num_vertices: int) -> tuple[tuple[int, int, int], ...]:
    """Compressed exact 1-minor Fitting-entry ideals of the Taylor differentials.

    Rows are ``(homological_degree, quotient_mask, multiplicity)``.  They are
    derived from the compressed DG differential entries by forgetting source
    and target multidegrees.
    """

    counts: dict[tuple[int, int], int] = {}
    for degree, _source_lcm, _target_lcm, quotient, multiplicity in cyclic_taylor_dg_differential_rows(num_vertices):
        key = (int(degree), int(quotient))
        counts[key] = counts.get(key, 0) + int(multiplicity)
    return tuple((degree, quotient, multiplicity) for (degree, quotient), multiplicity in sorted(counts.items()))


@functools.lru_cache(maxsize=64)
def cyclic_taylor_dg_product_summary_rows(num_vertices: int) -> tuple[dict[str, float], ...]:
    """Exact bidegree counts for the graded-commutative Taylor product."""

    generator_count = len(cyclic_stanley_reisner_generator_masks(num_vertices))
    rows: list[dict[str, float]] = []
    for left_degree in range(0, generator_count + 1):
        left_rank = math.comb(generator_count, left_degree)
        remaining = generator_count - left_degree
        for right_degree in range(0, remaining + 1):
            right_choices_per_left = math.comb(remaining, right_degree)
            product_count = left_rank * right_choices_per_left
            rows.append(
                {
                    "left_homological_degree": float(left_degree),
                    "right_homological_degree": float(right_degree),
                    "result_homological_degree": float(left_degree + right_degree),
                    "left_rank": float(left_rank),
                    "right_choices_per_left": float(right_choices_per_left),
                    "product_count": float(product_count),
                }
            )
    return tuple(rows)


@functools.lru_cache(maxsize=64)
def cyclic_taylor_fitting_summary_rows(num_vertices: int) -> tuple[dict[str, float], ...]:
    """Exact rank/count summary for Taylor-map Fitting determinantal ideals.

    The entry ideal rows above give the exact 1-minor Fitting ideal generators.
    Higher determinantal Fitting ideals can be astronomically large; this
    summary records the exact source/target ranks and exact combinatorial count
    of maximal minors in log10 form for each Taylor differential.
    """

    generator_count = len(cyclic_stanley_reisner_generator_masks(num_vertices))
    entry_rows = cyclic_taylor_fitting_entry_ideal_rows(num_vertices)
    entry_counts: dict[int, int] = {}
    for degree, _quotient, _multiplicity in entry_rows:
        entry_counts[int(degree)] = entry_counts.get(int(degree), 0) + 1

    rows: list[dict[str, float]] = []
    for degree in range(1, generator_count + 1):
        source_rank = math.comb(generator_count, degree)
        target_rank = math.comb(generator_count, degree - 1)
        maximal_minor_size = min(source_rank, target_rank)
        if maximal_minor_size == 0:
            maximal_minor_count_log10 = 0.0
        else:
            count_log = (
                math.lgamma(source_rank + 1)
                - math.lgamma(maximal_minor_size + 1)
                - math.lgamma(source_rank - maximal_minor_size + 1)
                + math.lgamma(target_rank + 1)
                - math.lgamma(maximal_minor_size + 1)
                - math.lgamma(target_rank - maximal_minor_size + 1)
            )
            maximal_minor_count_log10 = count_log / math.log(10.0)
        rows.append(
            {
                "homological_degree": float(degree),
                "source_rank": float(source_rank),
                "target_rank": float(target_rank),
                "boundary_terms": float(degree * source_rank),
                "entry_ideal_generator_count": float(entry_counts.get(degree, 0)),
                "maximal_minor_size": float(maximal_minor_size),
                "maximal_minor_count_log10": float(maximal_minor_count_log10),
            }
        )
    return tuple(rows)


def _simplices_by_dim(faces: frozenset[int], support: int) -> dict[int, list[int]]:
    out: dict[int, list[int]] = {}
    for face in faces:
        if face == 0 or face & ~support:
            continue
        dim = face.bit_count() - 1
        out.setdefault(dim, []).append(face)
    return out


def _boundary_rank(domain: list[int], codomain: list[int]) -> int:
    """Rank over F2 of the simplicial boundary matrix."""

    if not domain or not codomain:
        return 0
    row_index = {face: idx for idx, face in enumerate(codomain)}
    rows = [0 for _ in codomain]
    for col, simplex in enumerate(domain):
        bits = [i for i in range(simplex.bit_length()) if simplex & (1 << i)]
        for vertex in bits:
            boundary_face = simplex & ~(1 << vertex)
            idx = row_index.get(boundary_face)
            if idx is not None:
                rows[idx] ^= 1 << col
    return _rank_bitrows(rows)


def _rank_bitrows(rows: list[int]) -> int:
    basis: dict[int, int] = {}
    rank = 0
    for value in rows:
        x = int(value)
        while x:
            pivot = x.bit_length() - 1
            if pivot in basis:
                x ^= basis[pivot]
            else:
                basis[pivot] = x
                rank += 1
                break
    return rank


def reduced_homology_dim_f2(faces: frozenset[int], support: int, q: int) -> int:
    """Reduced homology dimension of the induced subcomplex on ``support``."""

    simplices = _simplices_by_dim(faces, support)
    vertex_count = len(simplices.get(0, []))
    if q == -1:
        return 1 if vertex_count == 0 else 0
    if q < -1:
        return 0
    n_q = len(simplices.get(q, []))
    if n_q == 0:
        return 0
    rank_boundary_q = 0 if q == 0 else _boundary_rank(simplices.get(q, []), simplices.get(q - 1, []))
    rank_boundary_next = _boundary_rank(simplices.get(q + 1, []), simplices.get(q, []))
    homology = n_q - rank_boundary_q - rank_boundary_next
    if q == 0 and vertex_count > 0:
        homology -= 1
    return max(0, int(homology))


@functools.lru_cache(maxsize=64)
def cyclic_stanley_reisner_resolution_metrics(num_vertices: int) -> SymbolicResolutionMetrics:
    """Exact symbolic resolution metrics for the cyclic fan complex."""

    n = max(1, int(num_vertices))
    faces = cyclic_flag_faces(n)
    nonfaces = cyclic_stanley_reisner_generator_masks(n)
    betti: dict[tuple[int, int], int] = {(0, 0): 1}
    for support in range(1, 1 << n):
        support_size = support.bit_count()
        for i in range(0, support_size + 1):
            q = support_size - i - 1
            dim = reduced_homology_dim_f2(faces, support, q)
            if dim:
                betti[(i, support)] = dim

    total_by_homological: dict[int, int] = {}
    for (degree, _support), value in betti.items():
        total_by_homological[degree] = total_by_homological.get(degree, 0) + value
    positive_betti = sum(value for (degree, _support), value in betti.items() if degree > 0)
    minimal_total = sum(betti.values())
    projective_dimension = max(total_by_homological, default=0)
    regularity = 0
    top_cardinality = 0
    for (degree, support), value in betti.items():
        if value <= 0:
            continue
        cardinality = support.bit_count()
        regularity = max(regularity, cardinality - degree)
        top_cardinality = max(top_cardinality, cardinality)

    generator_count = len(nonfaces)
    # Taylor resolution of S/I has F_0=S plus one basis element for every
    # nonempty subset of the monomial generators.
    taylor_positive_rank_log2 = float(generator_count)
    taylor_total_rank_log2 = math.log2(1.0 + 2.0**generator_count)
    if generator_count == 0:
        boundary_terms = 0.0
    else:
        # Sum_{p>=1} p C(g,p) = g 2^{g-1}.
        boundary_terms = float(generator_count) * (2.0 ** max(generator_count - 1, 0))
    taylor_boundary_terms_log2 = math.log2(max(boundary_terms, 1.0))
    nonminimality = max(0.0, (1.0 + 2.0**generator_count) - float(minimal_total))
    nonminimality_log2 = math.log2(max(nonminimality, 1.0))
    masses = [float(value) for value in total_by_homological.values() if value > 0]
    mass_sum = sum(masses)
    if mass_sum > 0.0 and len(masses) > 1:
        probs = [value / mass_sum for value in masses]
        entropy = -sum(p * math.log(p) for p in probs) / math.log(len(probs))
    else:
        entropy = 0.0

    return SymbolicResolutionMetrics(
        num_vertices=n,
        nonface_generator_count=generator_count,
        minimal_total_betti=int(minimal_total),
        minimal_positive_betti=int(positive_betti),
        taylor_total_rank_log2=float(taylor_total_rank_log2),
        taylor_positive_rank_log2=float(taylor_positive_rank_log2),
        taylor_boundary_terms_log2=float(taylor_boundary_terms_log2),
        nonminimality_log2=float(nonminimality_log2),
        projective_dimension=int(projective_dimension),
        regularity=int(regularity),
        betti0=int(total_by_homological.get(0, 0)),
        betti1=int(total_by_homological.get(1, 0)),
        betti2=int(total_by_homological.get(2, 0)),
        top_multidegree_cardinality=int(top_cardinality),
        betti_entropy=float(entropy),
    )


@functools.lru_cache(maxsize=64)
def cyclic_stanley_reisner_betti_rows(num_vertices: int) -> tuple[tuple[int, int, int, int], ...]:
    """Exact Hochster Betti rows ``(i, support_mask, support_size, beta)``."""

    n = max(1, int(num_vertices))
    faces = cyclic_flag_faces(n)
    rows: list[tuple[int, int, int, int]] = [(0, 0, 0, 1)]
    for support in range(1, 1 << n):
        support_size = support.bit_count()
        for i in range(0, support_size + 1):
            q = support_size - i - 1
            dim = reduced_homology_dim_f2(faces, support, q)
            if dim:
                rows.append((int(i), int(support), int(support_size), int(dim)))
    return tuple(rows)


def cyclic_stanley_reisner_resolution_dict(num_vertices: int) -> dict[str, float]:
    metrics = cyclic_stanley_reisner_resolution_metrics(num_vertices)
    return {
        "symbolic_resolution_num_vertices": float(metrics.num_vertices),
        "symbolic_resolution_nonface_generator_count": float(metrics.nonface_generator_count),
        "symbolic_resolution_minimal_total_betti": float(metrics.minimal_total_betti),
        "symbolic_resolution_minimal_positive_betti": float(metrics.minimal_positive_betti),
        "symbolic_resolution_taylor_total_rank_log2": float(metrics.taylor_total_rank_log2),
        "symbolic_resolution_taylor_positive_rank_log2": float(metrics.taylor_positive_rank_log2),
        "symbolic_resolution_taylor_boundary_terms_log2": float(metrics.taylor_boundary_terms_log2),
        "symbolic_resolution_nonminimality_log2": float(metrics.nonminimality_log2),
        "symbolic_resolution_projective_dimension": float(metrics.projective_dimension),
        "symbolic_resolution_regularity": float(metrics.regularity),
        "symbolic_resolution_betti0": float(metrics.betti0),
        "symbolic_resolution_betti1": float(metrics.betti1),
        "symbolic_resolution_betti2": float(metrics.betti2),
        "symbolic_resolution_top_multidegree_cardinality": float(metrics.top_multidegree_cardinality),
        "symbolic_resolution_betti_entropy": float(metrics.betti_entropy),
    }


def cyclic_stanley_reisner_resolution_certificate(num_vertices: int) -> dict[str, object]:
    """Return a machine-readable exact finite CCA/topology certificate.

    The certificate is intended for periodic sidecar analyses.  It records the
    actual finite combinatorial objects used to audit the train-time
    differentiable losses: faces, Stanley-Reisner generators, Hochster Betti
    rows, compressed Taylor multidegrees, and exact Taylor rank/boundary counts.
    """

    n = max(1, int(num_vertices))
    metrics = cyclic_stanley_reisner_resolution_metrics(n)
    face_rows = cyclic_flag_face_rows(n)
    nonfaces = cyclic_stanley_reisner_generator_masks(n)
    betti_rows = cyclic_stanley_reisner_betti_rows(n)
    taylor_rows = cyclic_taylor_multidegree_counts(n)
    taylor_rank_rows = cyclic_taylor_rank_rows(n)
    dg_rows = cyclic_taylor_dg_differential_rows(n)
    dg_product_rows = cyclic_taylor_dg_product_summary_rows(n)

    betti_table: dict[str, int] = {}
    for degree, _support, support_size, beta in betti_rows:
        key = f"{int(degree)}:{int(support_size)}"
        betti_table[key] = betti_table.get(key, 0) + int(beta)

    taylor_rank_by_degree = {
        str(int(degree)): int(rank) for degree, rank, _boundary_terms in taylor_rank_rows
    }
    taylor_boundary_terms_by_degree = {
        str(int(degree)): int(boundary_terms)
        for degree, _rank, boundary_terms in taylor_rank_rows
    }
    fitting_entry_rows = cyclic_taylor_fitting_entry_ideal_rows(n)
    fitting_summary_rows = cyclic_taylor_fitting_summary_rows(n)

    return {
        "kind": "cyclic_stanley_reisner_symbolic_resolution_certificate",
        "field": "F_2",
        "ring": {
            "kind": "multigraded_polynomial_ring",
            "field": "F_2",
            "variables": [f"x_{index}" for index in range(n)],
            "grading": "Z^n squarefree multigrading",
            "presentation": "F_2[" + ", ".join(f"x_{index}" for index in range(n)) + "]",
        },
        "num_vertices": int(n),
        "vertices": list(range(n)),
        "toric_fan": {
            "kind": "cyclic_one_skeleton_flag_fan",
            "vertices": list(range(n)),
            "rays": [f"rho_{index}" for index in range(n)],
            "one_dimensional_cones": [f"rho_{index}" for index in range(n)],
            "maximal_cones": [
                {
                    "mask": int((1 << index) | (1 << ((index + 1) % n))),
                    "vertices": [int(index), int((index + 1) % n)],
                    "monomial": squarefree_monomial((1 << index) | (1 << ((index + 1) % n)), n),
                }
                for index in range(n)
            ],
        },
        "faces": [
            {
                "dimension": int(dimension),
                "mask": int(mask),
                "vertices": list(mask_vertices(mask, n)),
                "monomial": squarefree_monomial(mask, n),
            }
            for dimension, mask, _cardinality in face_rows
        ],
        "stanley_reisner_ideal": {
            "kind": "squarefree_monomial_ideal",
            "quotient": "F_2[Delta] = F_2[x_0, ..., x_{n-1}] / I_Delta",
            "generator_count": int(len(nonfaces)),
            "generators": [
                {
                    "mask": int(mask),
                    "vertices": list(mask_vertices(mask, n)),
                    "degree": int(mask).bit_count(),
                    "multidegree": list(squarefree_exponent_vector(mask, n)),
                    "monomial": squarefree_monomial(mask, n),
                }
                for mask in nonfaces
            ],
        },
        "minimal_nonface_generators": [
            {
                "mask": int(mask),
                "vertices": list(mask_vertices(mask, n)),
                "degree": int(mask).bit_count(),
                "monomial": squarefree_monomial(mask, n),
            }
            for mask in nonfaces
        ],
        "hochster_betti_rows": [
            {
                "homological_degree": int(degree),
                "support_mask": int(support),
                "support_vertices": list(mask_vertices(support, n)),
                "support_size": int(support_size),
                "beta": int(beta),
            }
            for degree, support, support_size, beta in betti_rows
        ],
        "betti_table_by_homological_degree_and_support_size": [
            {
                "homological_degree": int(key.split(":")[0]),
                "support_size": int(key.split(":")[1]),
                "beta_total": int(value),
            }
            for key, value in sorted(
                betti_table.items(),
                key=lambda item: (int(item[0].split(":")[0]), int(item[0].split(":")[1])),
            )
        ],
        "taylor_multidegree_counts": [
            {
                "homological_degree": int(degree),
                "lcm_mask": int(mask),
                "lcm_vertices": list(mask_vertices(mask, n)),
                "lcm_support_size": int(mask).bit_count(),
                "multiplicity": int(multiplicity),
                "monomial": squarefree_monomial(mask, n),
            }
            for degree, mask, multiplicity in taylor_rows
        ],
        "taylor_rank_by_homological_degree": taylor_rank_by_degree,
        "taylor_boundary_terms_by_homological_degree": taylor_boundary_terms_by_degree,
        "dg_differential_entries": [
            {
                "homological_degree": int(degree),
                "source_lcm_mask": int(source_lcm),
                "source_lcm_vertices": list(mask_vertices(source_lcm, n)),
                "source_multidegree": list(squarefree_exponent_vector(source_lcm, n)),
                "source_monomial": squarefree_monomial(source_lcm, n),
                "target_lcm_mask": int(target_lcm),
                "target_lcm_vertices": list(mask_vertices(target_lcm, n)),
                "target_multidegree": list(squarefree_exponent_vector(target_lcm, n)),
                "target_monomial": squarefree_monomial(target_lcm, n),
                "quotient_mask": int(quotient),
                "quotient_vertices": list(mask_vertices(quotient, n)),
                "quotient_multidegree": list(squarefree_exponent_vector(quotient, n)),
                "quotient_monomial": squarefree_monomial(quotient, n),
                "multiplicity": int(multiplicity),
            }
            for degree, source_lcm, target_lcm, quotient, multiplicity in dg_rows
        ],
        "fitting_entry_ideal_generators": [
            {
                "homological_degree": int(degree),
                "quotient_mask": int(mask),
                "quotient_vertices": list(mask_vertices(mask, n)),
                "quotient_multidegree": list(squarefree_exponent_vector(mask, n)),
                "monomial": squarefree_monomial(mask, n),
                "multiplicity": int(multiplicity),
            }
            for degree, mask, multiplicity in fitting_entry_rows
        ],
        "fitting_determinantal_summary": [
            {
                "homological_degree": int(row["homological_degree"]),
                "source_rank": int(row["source_rank"]),
                "target_rank": int(row["target_rank"]),
                "boundary_terms": int(row["boundary_terms"]),
                "entry_ideal_generator_count": int(row["entry_ideal_generator_count"]),
                "maximal_minor_size": int(row["maximal_minor_size"]),
                "maximal_minor_count_log10": float(row["maximal_minor_count_log10"]),
            }
            for row in fitting_summary_rows
        ],
        "dg_product_summary_by_bidegree": [
            {
                "left_homological_degree": int(row["left_homological_degree"]),
                "right_homological_degree": int(row["right_homological_degree"]),
                "result_homological_degree": int(row["result_homological_degree"]),
                "left_rank": int(row["left_rank"]),
                "right_choices_per_left": int(row["right_choices_per_left"]),
                "product_count": int(row["product_count"]),
            }
            for row in dg_product_rows
        ],
        "dg_algebra": {
            "basis": "Taylor exterior basis e_A over subsets of Stanley-Reisner generators",
            "product": "e_A * e_B = e_{A union B} for disjoint generator subsets, zero otherwise over F_2 signs",
            "differential": "Taylor differential with lcm monomial quotients",
            "augmentation_ideal_generator_count": int(metrics.nonface_generator_count),
            "d_squared_zero": True,
            "leibniz_rule": True,
        },
        "metrics": cyclic_stanley_reisner_resolution_dict(n),
    }
